INSERT INTO courses (
  id,
  org_id,
  title,
  slug,
  description,
  long_description,
  thumbnail_url,
  category,
  level,
  duration_hours,
  price_cents,
  currency,
  is_public,
  is_featured,
  status,
  instructor_id,
  metadata,
  created_at,
  updated_at,
  published_at
) VALUES (
  'course_connor_platform_operator',
  'org_leadership_legacy',
  'Connor Platform Operator: Leadership Legacy Digital',
  'connor-platform-operator',
  'Hands-on operator course for Connor to run, test, deploy, secure, and extend the Leadership Legacy Digital platform.',
  'A practical course covering repo fundamentals, Cloudflare Workers, R2, D1, KV, Durable Objects, Agent Connor, OpenAI, GitHub, Google Drive, Gmail, Resend, Supabase, MCP-style tools, Playwright, R2 deploy snapshots, pruning, and final production readiness.',
  NULL,
  'ai-engineering-operations',
  'beginner-to-intermediate',
  18,
  0,
  'usd',
  0,
  1,
  'published',
  'agent_sam',
  '{"workspace_id":"ws_connor_mcneely","github_repo":"SamPrimeaux/leadership-legacy","r2_bucket":"leadership-legacy","live_url":"https://leadership-legacy.meauxbility.workers.dev","blocked_models":["gpt-5.5","gpt-5.5-pro","gpt-5.4-pro"],"default_model":"gpt-5.4-mini","rubric_version":"2026-05-07"}',
  unixepoch(),
  unixepoch(),
  unixepoch()
)
ON CONFLICT(org_id, slug) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  long_description = excluded.long_description,
  thumbnail_url = excluded.thumbnail_url,
  category = excluded.category,
  level = excluded.level,
  duration_hours = excluded.duration_hours,
  price_cents = excluded.price_cents,
  currency = excluded.currency,
  is_public = excluded.is_public,
  is_featured = excluded.is_featured,
  status = excluded.status,
  instructor_id = excluded.instructor_id,
  metadata = excluded.metadata,
  updated_at = unixepoch(),
  published_at = unixepoch();
