INSERT INTO course_lessons (
  id, module_id, course_id, title, type, description, estimated_minutes,
  order_index, is_required, created_at, updated_at, content,
  content_format, has_content, sandbox_query, sandbox_db
) VALUES
(
  'lesson_01_repo_map',
  'mod_01_repo_foundation',
  'course_connor_platform_operator',
  'Understand the Leadership Legacy repo map',
  'lesson',
  'Learn the difference between source, generated output, scripts, docs, tests, and ignored folders.',
  20,
  1,
  1,
  unixepoch(),
  unixepoch(),
  'Repo Map: src is source code, src/public-app is the public React app, src/dashboard is the dashboard and Agent Connor UI, src/worker is the Cloudflare Worker API/router, docs are operating guides, scripts are automation helpers, tests/e2e are Playwright tests, dist is generated build output and should never be committed, node_modules is installed dependencies and should never be committed.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_02_local_install',
  'mod_01_repo_foundation',
  'course_connor_platform_operator',
  'Install and run locally',
  'lab',
  'Install dependencies and run the local Vite dev server.',
  35,
  2,
  1,
  unixepoch(),
  unixepoch(),
  'Run npm install --include=dev, then npm run dev. Connor should know how to stop a process with Ctrl+C, restart the dev server, and read terminal errors.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_03_build_basics',
  'mod_01_repo_foundation',
  'course_connor_platform_operator',
  'Build and inspect generated output',
  'lab',
  'Run the production build and inspect generated dist assets.',
  35,
  3,
  1,
  unixepoch(),
  unixepoch(),
  'Run npm run build. Expected output includes dist/index.html, dist/dashboard.html, and dist/assets. dist is generated output and should stay gitignored.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_04_worker_health',
  'mod_02_cloudflare_runtime',
  'course_connor_platform_operator',
  'Verify Worker health and API routes',
  'lab',
  'Verify live Worker, provider status, OpenAI configured status, and R2 binding status.',
  30,
  1,
  1,
  unixepoch(),
  unixepoch(),
  'Run curl against /api/health and /api/ai/providers. Connor should explain worker online status, OpenAI configured status, R2 binding status, provider status, and blocked model policy.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_05_r2_browser',
  'mod_02_cloudflare_runtime',
  'course_connor_platform_operator',
  'R2 storage and object listing',
  'lab',
  'Use the dashboard storage page and Worker R2 list API.',
  40,
  2,
  1,
  unixepoch(),
  unixepoch(),
  'Use /dashboard/storage and quoted curl URLs for /api/r2/list?prefix= and /api/r2/list?prefix=deployments/. In zsh, quote URLs that contain question marks.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_06_r2_deploy_prune',
  'mod_02_cloudflare_runtime',
  'course_connor_platform_operator',
  'R2 deploy snapshots and pruning',
  'lesson',
  'Understand live assets, deployment snapshots, and safe R2 pruning.',
  45,
  3,
  1,
  unixepoch(),
  unixepoch(),
  'Builds upload to live/, deployments/<sha>/, and deployments/_latest.json. Pruning deletes only old deployments/<old-sha>/ snapshots and must never delete live/, cms/, assets/, docs/, or analytics/.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_07_d1_kv_do_plan',
  'mod_02_cloudflare_runtime',
  'course_connor_platform_operator',
  'D1, KV, and Durable Object responsibilities',
  'lesson',
  'Understand which Cloudflare storage/runtime primitive owns which responsibility.',
  35,
  4,
  1,
  unixepoch(),
  unixepoch(),
  'D1 should hold CMS runtime data. KV should hold short-lived state. Durable Objects should hold realtime state for agent sessions, terminal sessions, collaboration, and live CMS editing.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_08_openai_diagnostics',
  'mod_03_agent_connor_ai',
  'course_connor_platform_operator',
  'OpenAI diagnostics and secret hygiene',
  'lab',
  'Verify OpenAI key shape and live test without exposing secrets.',
  35,
  1,
  1,
  unixepoch(),
  unixepoch(),
  'Run /api/openai/diagnostics and /api/openai/test. Expected: startsWithEnvName false, hasQuotes false, and text ok. The browser must never see OPENAI_API_KEY.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_09_agent_chat_code_auto',
  'mod_03_agent_connor_ai',
  'course_connor_platform_operator',
  'Agent Connor Chat, Code, and Auto modes',
  'lab',
  'Learn when Agent Connor should chat versus edit the active Monaco file.',
  45,
  2,
  1,
  unixepoch(),
  unixepoch(),
  'Chat is the default. Use Code only when intentionally editing the active Monaco file. Auto should switch to code only for clear edit/refactor/patch prompts.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_10_provider_policy',
  'mod_03_agent_connor_ai',
  'course_connor_platform_operator',
  'Provider lanes and blocked model policy',
  'lesson',
  'Understand active model lanes, blocked models, and planned providers.',
  35,
  3,
  1,
  unixepoch(),
  unixepoch(),
  'Current OpenAI lanes are gpt-5.4-nano, gpt-5.4-mini, and gpt-5.4. Blocked models are gpt-5.5, gpt-5.5-pro, and gpt-5.4-pro. Planned providers include Anthropic, Gemini, Workers AI, and local Llama/Ollama.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_11_cost_quality_tracking',
  'mod_03_agent_connor_ai',
  'course_connor_platform_operator',
  'Cost, quality, and routing evaluation',
  'lesson',
  'Learn the core telemetry required for model routing and quality gates.',
  35,
  4,
  1,
  unixepoch(),
  unixepoch(),
  'A real agent platform should track provider, model, tokens, latency, cost, tool success, test pass/fail, human rating, and rubric score.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_12_dashboard_routes',
  'mod_04_dashboard_ide',
  'course_connor_platform_operator',
  'Dashboard route map',
  'lesson',
  'Understand the dashboard route map and what each page is for.',
  25,
  1,
  1,
  unixepoch(),
  unixepoch(),
  'Dashboard routes include /dashboard, /dashboard/agent, /dashboard/storage, /dashboard/settings, /dashboard/analytics, /dashboard/learn, /dashboard/mail, and /dashboard/mcp. Monaco should dominate only the Agent IDE route.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_13_monaco_workflow',
  'mod_04_dashboard_ide',
  'course_connor_platform_operator',
  'Monaco edit workflow',
  'lab',
  'Use Monaco and Agent Connor safely without committing blindly.',
  40,
  2,
  1,
  unixepoch(),
  unixepoch(),
  'Connor should open a seeded file, open a text R2 object, ask Agent Connor to explain it, switch to Code mode, generate an edit, review the result, and apply to editor without committing blindly.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_14_terminal_prep',
  'mod_04_dashboard_ide',
  'course_connor_platform_operator',
  'Terminal and command cockpit',
  'lab',
  'Understand the xterm command cockpit and future PTY tunnel architecture.',
  35,
  3,
  1,
  unixepoch(),
  unixepoch(),
  'The xterm panel is a command cockpit. It is not yet a fully connected PTY. Future path: Dashboard to Worker Auth to Durable Object to PTY/Tunnel.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_15_cms_runtime_plan',
  'mod_04_dashboard_ide',
  'course_connor_platform_operator',
  'CMS runtime design',
  'lesson',
  'Understand the future CMS page, section, asset, SEO, draft, and publishing runtime.',
  60,
  4,
  1,
  unixepoch(),
  unixepoch(),
  'CMS should support pages, sections, services, case studies, resources, SEO, navigation, assets, drafts, publishing, and version history.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_16_github_integration',
  'mod_05_integrations',
  'course_connor_platform_operator',
  'GitHub OAuth/App workflow',
  'lesson',
  'Understand planned GitHub OAuth/App capabilities and approval-gated repo writes.',
  45,
  1,
  1,
  unixepoch(),
  unixepoch(),
  'Planned GitHub features include repo listing, tree browsing, opening files into Monaco, AI edit, diff preview, branch commit, PR creation, tests, and deploy after approval.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_17_google_drive_gmail',
  'mod_05_integrations',
  'course_connor_platform_operator',
  'Google Drive and Gmail OAuth',
  'lesson',
  'Understand planned Google Drive import and Gmail draft workflows.',
  45,
  2,
  1,
  unixepoch(),
  unixepoch(),
  'Drive should support docs/PDF import into R2 and RAG. Gmail should support thread summaries and approval-gated draft replies. Tokens must never live in browser localStorage.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_18_resend_email',
  'mod_05_integrations',
  'course_connor_platform_operator',
  'Resend transactional email',
  'lesson',
  'Understand planned Resend notification and transactional email flows.',
  30,
  3,
  1,
  unixepoch(),
  unixepoch(),
  'Use Resend for contact notifications, lead confirmations, admin invites, password reset or magic link later, and deploy notifications.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_19_supabase_analytics_rag',
  'mod_05_integrations',
  'course_connor_platform_operator',
  'Supabase analytics, RAG, and evals',
  'lesson',
  'Understand Supabase responsibilities for analytics, RAG, evals, and long-term telemetry.',
  45,
  4,
  1,
  unixepoch(),
  unixepoch(),
  'Supabase should hold analytics, RAG documents, pgvector embeddings, eval runs, routing logs, codebase chunks, tool execution logs, and long-term telemetry.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_20_mcp_tool_registry',
  'mod_05_integrations',
  'course_connor_platform_operator',
  'MCP-style tool registry and approval gates',
  'lesson',
  'Understand MCP-style tool schemas, risk levels, logs, and approval requirements.',
  45,
  5,
  1,
  unixepoch(),
  unixepoch(),
  'Tools need input schema, output schema, risk level, approval requirement, rate limit, execution logs, error logs, and cost tracking.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_21_playwright_live',
  'mod_06_testing_release',
  'course_connor_platform_operator',
  'Live Playwright smoke testing',
  'lab',
  'Run live Playwright smoke tests and understand why failures should block deploy.',
  45,
  1,
  1,
  unixepoch(),
  unixepoch(),
  'Run npm run test:e2e. Failed tests should block deploy until understood.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_22_github_actions',
  'mod_06_testing_release',
  'course_connor_platform_operator',
  'GitHub Actions autodeploy',
  'lesson',
  'Understand the GitHub Actions build, test, R2 publish, prune, and deploy flow.',
  40,
  2,
  1,
  unixepoch(),
  unixepoch(),
  'On push to main: install, audit, build, test, upload dist to R2, prune old R2 deployments, and deploy Worker.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_23_release_checklist',
  'mod_06_testing_release',
  'course_connor_platform_operator',
  'Manual release checklist',
  'lab',
  'Run and explain the manual release checklist up to the approval point.',
  45,
  3,
  1,
  unixepoch(),
  unixepoch(),
  'Run git pull origin main, npm install --include=dev, npm run build, npm run test:e2e, npm run deploy:full, and git status --short.',
  'markdown',
  1,
  NULL,
  'd1'
),
(
  'lesson_24_final_handoff',
  'mod_06_testing_release',
  'course_connor_platform_operator',
  'Final production readiness review',
  'assessment',
  'Demonstrate operator readiness and score the platform with the final rubric.',
  50,
  4,
  1,
  unixepoch(),
  unixepoch(),
  'Connor should demonstrate local run, build, test, deploy, OpenAI verification, R2 verification, security rules, approval gates, integration roadmap, and rubric scoring.',
  'markdown',
  1,
  NULL,
  'd1'
)
ON CONFLICT(id) DO UPDATE SET
  module_id = excluded.module_id,
  course_id = excluded.course_id,
  title = excluded.title,
  type = excluded.type,
  description = excluded.description,
  estimated_minutes = excluded.estimated_minutes,
  order_index = excluded.order_index,
  is_required = excluded.is_required,
  updated_at = unixepoch(),
  content = excluded.content,
  content_format = excluded.content_format,
  has_content = excluded.has_content,
  sandbox_query = excluded.sandbox_query,
  sandbox_db = excluded.sandbox_db;
