INSERT INTO course_assignments (
  id,
  course_id,
  module_id,
  lesson_id,
  title,
  description,
  type,
  rubric,
  max_score,
  required_evidence,
  due_offset_days,
  is_graded,
  created_at,
  updated_at
) VALUES
(
  'assign_01_repo_map',
  'course_connor_platform_operator',
  'mod_01_repo_foundation',
  'lesson_01_repo_map',
  'Repo map explanation',
  'Explain the repo structure and identify source, generated, docs, scripts, tests, and ignored folders.',
  'written',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'A short written repo map plus output of git status --short.',
  1,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_02_local_run',
  'course_connor_platform_operator',
  'mod_01_repo_foundation',
  'lesson_02_local_install',
  'Local app run proof',
  'Install dependencies and run the app locally.',
  'lab',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Terminal output for npm install --include=dev and npm run dev, plus local URL note.',
  1,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_03_build_output',
  'course_connor_platform_operator',
  'mod_01_repo_foundation',
  'lesson_03_build_basics',
  'Build output inspection',
  'Run a production build and explain why dist/ is not committed.',
  'lab',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'npm run build output and explanation of dist/ and node_modules/ gitignore rules.',
  2,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_04_worker_health',
  'course_connor_platform_operator',
  'mod_02_cloudflare_runtime',
  'lesson_04_worker_health',
  'Worker health verification',
  'Verify live Worker and provider status endpoints.',
  'lab',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Outputs from /api/health and /api/ai/providers.',
  2,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_05_r2_listing',
  'course_connor_platform_operator',
  'mod_02_cloudflare_runtime',
  'lesson_05_r2_browser',
  'R2 listing and zsh URL quoting',
  'List R2 root and deployments prefix through the Worker API and explain zsh URL quoting.',
  'lab',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Outputs from quoted curl commands for /api/r2/list?prefix= and /api/r2/list?prefix=deployments/.',
  3,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_06_r2_prune_safety',
  'course_connor_platform_operator',
  'mod_02_cloudflare_runtime',
  'lesson_06_r2_deploy_prune',
  'R2 prune safety review',
  'Explain what the prune script deletes and what it must never delete.',
  'written',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Written answer identifying deployments/<old-sha>/ as deletable and live/cms/assets/docs/analytics as protected.',
  3,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_07_openai_diagnostics',
  'course_connor_platform_operator',
  'mod_03_agent_connor_ai',
  'lesson_08_openai_diagnostics',
  'OpenAI diagnostic proof',
  'Verify OpenAI secret shape and live OpenAI test.',
  'lab',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Outputs from /api/openai/diagnostics and /api/openai/test with no secret exposed.',
  4,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_08_agent_modes',
  'course_connor_platform_operator',
  'mod_03_agent_connor_ai',
  'lesson_09_agent_chat_code_auto',
  'Agent Connor mode demonstration',
  'Demonstrate Chat, Code, and Auto modes and explain when each should be used.',
  'demo',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Screenshots or notes showing Chat answer, Code file edit, and Auto behavior.',
  4,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_09_model_policy',
  'course_connor_platform_operator',
  'mod_03_agent_connor_ai',
  'lesson_10_provider_policy',
  'Provider and model policy explanation',
  'Explain enabled OpenAI lanes, blocked models, and planned provider roles.',
  'written',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Written model policy summary and provider status output.',
  5,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_10_dashboard_route_review',
  'course_connor_platform_operator',
  'mod_04_dashboard_ide',
  'lesson_12_dashboard_routes',
  'Dashboard route review',
  'Visit every dashboard route and summarize its purpose.',
  'audit',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Checklist of all dashboard routes with one-line purpose each.',
  5,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_11_monaco_r2_open',
  'course_connor_platform_operator',
  'mod_04_dashboard_ide',
  'lesson_13_monaco_workflow',
  'Open R2 text object into Monaco',
  'Use the storage browser to open a text/code object into Monaco.',
  'lab',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Screenshot or notes showing R2 object opened into Monaco.',
  6,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_12_terminal_plan',
  'course_connor_platform_operator',
  'mod_04_dashboard_ide',
  'lesson_14_terminal_prep',
  'Terminal architecture explanation',
  'Explain current terminal cockpit and future Worker Auth to Durable Object to PTY/Tunnel path.',
  'written',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Short architecture explanation including approval requirement for terminal commands.',
  6,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_13_github_plan',
  'course_connor_platform_operator',
  'mod_05_integrations',
  'lesson_16_github_integration',
  'GitHub integration implementation plan',
  'Design GitHub OAuth/App path for repo browsing, file editing, branch commits, and PR creation.',
  'design',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'One-page plan with required secrets, routes, and approval gates.',
  7,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_14_google_mail_plan',
  'course_connor_platform_operator',
  'mod_05_integrations',
  'lesson_17_google_drive_gmail',
  'Google Drive and Gmail OAuth plan',
  'Design Drive import and Gmail draft workflows with token safety rules.',
  'design',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'OAuth scopes, callback URL, token storage plan, and approval-gated Gmail draft flow.',
  7,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_15_mcp_registry',
  'course_connor_platform_operator',
  'mod_05_integrations',
  'lesson_20_mcp_tool_registry',
  'MCP tool registry safety matrix',
  'Classify first MCP tools by risk level and approval requirement.',
  'deliverable',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Tool matrix with key, risk, approval required, input/output notes, and expected logs.',
  8,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_16_live_playwright',
  'course_connor_platform_operator',
  'mod_06_testing_release',
  'lesson_21_playwright_live',
  'Run live Playwright tests',
  'Run live Playwright tests and interpret any failures.',
  'lab',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'npm run test:e2e output and short notes on pass/fail status.',
  8,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_17_release_dry_run',
  'course_connor_platform_operator',
  'mod_06_testing_release',
  'lesson_23_release_checklist',
  'Manual release dry run',
  'Perform the release checklist up to the approval point and explain each command.',
  'demo',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"correctness","label":"Correctness","weight":25,"description":"The task works as requested and uses the correct route, command, or workflow."},{"key":"safety","label":"Safety and secrets","weight":20,"description":"No secrets are exposed; risky/destructive actions are identified and approval-gated."},{"key":"evidence","label":"Evidence quality","weight":20,"description":"Submission includes commands, outputs, screenshots, links, or notes proving completion."},{"key":"understanding","label":"Conceptual understanding","weight":20,"description":"Connor can explain what happened, why it matters, and how to debug it."},{"key":"independence","label":"Operator independence","weight":15,"description":"Connor can repeat the workflow with minimal help."}],"pass_score":80,"distinction_score":92}',
  100,
  'Commands run, outputs, and note identifying which commands mutate production.',
  9,
  1,
  unixepoch(),
  unixepoch()
),
(
  'assign_18_final_readiness',
  'course_connor_platform_operator',
  'mod_06_testing_release',
  'lesson_24_final_handoff',
  'Final production readiness review',
  'Use full rubric to score Connor/operator readiness and platform readiness.',
  'assessment',
  '{"scale":{"0":"Not present","1":"Started but not usable","2":"Partially usable with manual work","3":"Usable for internal testing","4":"Production-ready with guardrails","5":"Production-ready, monitored, documented, and tested"},"criteria":[{"key":"repo_ops","label":"Repo operations","weight":15,"description":"Can clone, install, build, test, and explain repo structure."},{"key":"cloudflare_ops","label":"Cloudflare operations","weight":15,"description":"Can verify Worker, R2, secrets, and deployment state."},{"key":"ai_ops","label":"AI operations","weight":15,"description":"Can verify OpenAI, explain provider lanes, and use Agent modes safely."},{"key":"integration_plan","label":"Integration plan","weight":15,"description":"Can explain GitHub, Google, Resend, Supabase, and MCP roadmap."},{"key":"testing_release","label":"Testing and release","weight":20,"description":"Can run Playwright and understand deploy/R2 prune flow."},{"key":"security","label":"Security and approvals","weight":20,"description":"Can identify secrets, risky tools, and required approvals."}],"pass_score":85,"distinction_score":94}',
  100,
  'Completed readiness matrix with scores, evidence links/notes, and next actions.',
  10,
  1,
  unixepoch(),
  unixepoch()
)
ON CONFLICT(id) DO UPDATE SET
  course_id = excluded.course_id,
  module_id = excluded.module_id,
  lesson_id = excluded.lesson_id,
  title = excluded.title,
  description = excluded.description,
  type = excluded.type,
  rubric = excluded.rubric,
  max_score = excluded.max_score,
  required_evidence = excluded.required_evidence,
  due_offset_days = excluded.due_offset_days,
  is_graded = excluded.is_graded,
  updated_at = unixepoch();
